# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Envee < Formula
  desc "Per-directory environment variable manager (pre-release)"
  homepage "https://github.com/baken667/envee"
  version "0.3.0-rc.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/baken667/envee/releases/download/v0.3.0-rc.1/envee_0.3.0-rc.1_darwin_amd64.tar.gz"
      sha256 "90e249b8dd2ffd2cd36cfec2535163a78e37ca1f619f0c9ff1d55988cf6ba401"

      def install
        bin.install "envee"
        bin.install "enveed"
        bash_completion.install "completions/envee.bash" => "envee"
        zsh_completion.install "completions/envee.zsh" => "_envee"
        fish_completion.install "completions/envee.fish"
        man1.install Dir["manpages/*.1"]
      end
    end
    on_arm do
      url "https://github.com/baken667/envee/releases/download/v0.3.0-rc.1/envee_0.3.0-rc.1_darwin_arm64.tar.gz"
      sha256 "9bea972ff0a8e41e0a1e71a5d3841d9d92a551c3c5d2719ac87fa807d3f290fb"

      def install
        bin.install "envee"
        bin.install "enveed"
        bash_completion.install "completions/envee.bash" => "envee"
        zsh_completion.install "completions/envee.zsh" => "_envee"
        fish_completion.install "completions/envee.fish"
        man1.install Dir["manpages/*.1"]
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/baken667/envee/releases/download/v0.3.0-rc.1/envee_0.3.0-rc.1_linux_amd64.tar.gz"
        sha256 "1b1101756692eccb9f42ef3de6184b1e286c7cd1ad7f53da2e1376d2d0c8ced3"

        def install
          bin.install "envee"
          bin.install "enveed"
          bash_completion.install "completions/envee.bash" => "envee"
          zsh_completion.install "completions/envee.zsh" => "_envee"
          fish_completion.install "completions/envee.fish"
          man1.install Dir["manpages/*.1"]
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/baken667/envee/releases/download/v0.3.0-rc.1/envee_0.3.0-rc.1_linux_arm64.tar.gz"
        sha256 "f8d2e14884d44ad10d8de3b34ef227c55c1013a7df5db1b5c9233deccc388735"

        def install
          bin.install "envee"
          bin.install "enveed"
          bash_completion.install "completions/envee.bash" => "envee"
          zsh_completion.install "completions/envee.zsh" => "_envee"
          fish_completion.install "completions/envee.fish"
          man1.install Dir["manpages/*.1"]
        end
      end
    end
  end

  def caveats
    <<~EOS
      ⚠️  STAGING BUILD — this is a pre-release from the staging tap.
      Use only for testing. To remove:

          brew uninstall baken667/tap-staging/envee

      To enable envee in your shell, add one of these to your config:
        bash:  eval "$(envee init bash)"
        zsh:   eval "$(envee init zsh)"
        fish:  envee init fish | source
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/envee --version")
    assert_match "_envee_hook", shell_output("#{bin}/envee init bash")
    assert_match "add-zsh-hook", shell_output("#{bin}/envee init zsh")
    # Kept in sync with the production config deliberately. This assertion
    # was missing here, so the pre-release channel did not exercise the fish
    # hook -- which is precisely the one that shipped broken in v0.2.0.
    assert_match "_envee_hook", shell_output("#{bin}/envee init fish")
  end
end
