# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Envee < Formula
  desc "Per-directory environment variable manager (pre-release)"
  homepage "https://github.com/baken667/envee"
  version "0.4.0-rc.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/baken667/envee/releases/download/v0.4.0-rc.1/envee_0.4.0-rc.1_darwin_amd64.tar.gz"
      sha256 "1b5b769265d5897ba1581677ff725cc707d9427d8537b77f31da7b5fbd98a771"

      def install
        bin.install "envee"
        bin.install "enveed"
        bash_completion.install "completions/envee.bash" => "envee"
        zsh_completion.install "completions/envee.zsh" => "_envee"
        fish_completion.install "completions/envee.fish"
        man1.install Dir["manpages/*.1"]
      end
    end
    on_arm do
      url "https://github.com/baken667/envee/releases/download/v0.4.0-rc.1/envee_0.4.0-rc.1_darwin_arm64.tar.gz"
      sha256 "cdd5de241ac3d47d712f7fb274456d9867ca0dc34b974e3ef6d30c07e5cf7a3f"

      def install
        bin.install "envee"
        bin.install "enveed"
        bash_completion.install "completions/envee.bash" => "envee"
        zsh_completion.install "completions/envee.zsh" => "_envee"
        fish_completion.install "completions/envee.fish"
        man1.install Dir["manpages/*.1"]
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/baken667/envee/releases/download/v0.4.0-rc.1/envee_0.4.0-rc.1_linux_amd64.tar.gz"
        sha256 "d3d749e522265dc36d18e8538b9ae459ff37f72d4c11dd6e513188fab28f0dd0"

        def install
          bin.install "envee"
          bin.install "enveed"
          bash_completion.install "completions/envee.bash" => "envee"
          zsh_completion.install "completions/envee.zsh" => "_envee"
          fish_completion.install "completions/envee.fish"
          man1.install Dir["manpages/*.1"]
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/baken667/envee/releases/download/v0.4.0-rc.1/envee_0.4.0-rc.1_linux_arm64.tar.gz"
        sha256 "85402ba3f10c2018376b1620b6d8b5df34b3111a9a22e1471635976816a080a3"

        def install
          bin.install "envee"
          bin.install "enveed"
          bash_completion.install "completions/envee.bash" => "envee"
          zsh_completion.install "completions/envee.zsh" => "_envee"
          fish_completion.install "completions/envee.fish"
          man1.install Dir["manpages/*.1"]
        end
      end
    end
  end

  def caveats
    <<~EOS
      ⚠️  STAGING BUILD — this is a pre-release from the staging tap.
      Use only for testing. To remove:

          brew uninstall baken667/tap-staging/envee

      To enable envee in your shell, add one of these to your config:
        bash:  eval "$(envee init bash)"
        zsh:   eval "$(envee init zsh)"
        fish:  envee init fish | source
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/envee --version")
    assert_match "_envee_hook", shell_output("#{bin}/envee init bash")
    assert_match "add-zsh-hook", shell_output("#{bin}/envee init zsh")
    # Kept in sync with the production config deliberately. This assertion
    # was missing here, so the pre-release channel did not exercise the fish
    # hook -- which is precisely the one that shipped broken in v0.2.0.
    assert_match "_envee_hook", shell_output("#{bin}/envee init fish")
  end
end
