# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Envee < Formula
  desc "Per-directory environment variable manager (pre-release)"
  homepage "https://github.com/baken667/envee"
  version "0.1.1-rc.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/baken667/envee/releases/download/v0.1.1-rc.1/envee_0.1.1-rc.1_darwin_amd64.tar.gz"
      sha256 "bd3402303fd69366af3c32729156820b43891809d2a0cdc442e0844d82de385f"

      def install
        bin.install "envee"
        bin.install "enveed"
        bash_completion.install "completions/envee.bash" => "envee"
        zsh_completion.install "completions/envee.zsh" => "_envee"
        fish_completion.install "completions/envee.fish"
        man1.install Dir["manpages/*.1"]
      end
    end
    on_arm do
      url "https://github.com/baken667/envee/releases/download/v0.1.1-rc.1/envee_0.1.1-rc.1_darwin_arm64.tar.gz"
      sha256 "90ca2d59973f200860cfab4ccbe9a329f7d5e08e8283bc33ef11475675592999"

      def install
        bin.install "envee"
        bin.install "enveed"
        bash_completion.install "completions/envee.bash" => "envee"
        zsh_completion.install "completions/envee.zsh" => "_envee"
        fish_completion.install "completions/envee.fish"
        man1.install Dir["manpages/*.1"]
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/baken667/envee/releases/download/v0.1.1-rc.1/envee_0.1.1-rc.1_linux_amd64.tar.gz"
        sha256 "c25477d81d318077dd55bc77c211d1d48b99c55da73a17e9083a50c36ecf31c2"

        def install
          bin.install "envee"
          bin.install "enveed"
          bash_completion.install "completions/envee.bash" => "envee"
          zsh_completion.install "completions/envee.zsh" => "_envee"
          fish_completion.install "completions/envee.fish"
          man1.install Dir["manpages/*.1"]
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/baken667/envee/releases/download/v0.1.1-rc.1/envee_0.1.1-rc.1_linux_arm64.tar.gz"
        sha256 "914ab0da72d3606aa1cc50d4fc6f265770c7d4cbee13054b585d334f0fc61aa3"

        def install
          bin.install "envee"
          bin.install "enveed"
          bash_completion.install "completions/envee.bash" => "envee"
          zsh_completion.install "completions/envee.zsh" => "_envee"
          fish_completion.install "completions/envee.fish"
          man1.install Dir["manpages/*.1"]
        end
      end
    end
  end

  def caveats
    <<~EOS
      ⚠️  STAGING BUILD — this is a pre-release from the staging tap.
      Use only for testing. To remove:

          brew uninstall baken667/tap-staging/envee

      To enable envee in your shell, add one of these to your config:
        bash:  eval "$(envee init bash)"
        zsh:   eval "$(envee init zsh)"
        fish:  envee init fish | source
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/envee --version")
    assert_match "_envee_hook", shell_output("#{bin}/envee init bash")
    assert_match "add-zsh-hook", shell_output("#{bin}/envee init zsh")
  end
end
